apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-workflow
spec:
  template:
    spec:
      containers:
        - name: workflow
          env:
            - name: OSDU_AIRFLOW_ENABLED
              value: "true"
            - name: OSDU_AIRFLOW_URL
              value: "http://airflow-webserver.osdu-airflow.svc.cluster.local:8080"
            - name: OSDU_AIRFLOW_USERNAME
              value: "admin"
            - name: OSDU_AIRFLOW_PASSWORD
              value: "Airflow@2026"
