apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osdu-airflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  project: default
  source:
    chart: airflow
    repoURL: https://airflow.apache.org
    targetRevision: 1.16.0
    helm:
      releaseName: airflow
  destination:
    server: https://kubernetes.default.svc
    namespace: osdu-airflow
  # No syncPolicy = manual only, observe mode
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /spec
        - /data
        - /metadata/annotations
