apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: osdu-opensearch-proxy:apps/Deployment:osdu-data/opensearch-proxy
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"osdu-opensearch-proxy:apps/Deployment:osdu-data/opensearch-proxy"},"labels":{"app":"opensearch-proxy"},"name":"opensearch-proxy","namespace":"osdu-data"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"opensearch-proxy"}},"template":{"metadata":{"labels":{"app":"opensearch-proxy"}},"spec":{"containers":[{"image":"nginx:1.25-alpine","livenessProbe":{"httpGet":{"path":"/health","port":9200},"initialDelaySeconds":5,"periodSeconds":10},"name":"nginx","ports":[{"containerPort":9200,"name":"http"}],"readinessProbe":{"httpGet":{"path":"/health","port":9200},"initialDelaySeconds":5,"periodSeconds":5},"resources":{"limits":{"cpu":"200m","memory":"128Mi"},"requests":{"cpu":"50m","memory":"64Mi"}},"volumeMounts":[{"mountPath":"/etc/nginx/nginx.conf","name":"config","readOnly":true,"subPath":"nginx.conf"}]}],"volumes":[{"configMap":{"name":"opensearch-proxy-config"},"name":"config"}]}}}}
  creationTimestamp: "2026-01-26T10:02:16Z"
  generation: 6
  labels:
    app: opensearch-proxy
  name: opensearch-proxy
  namespace: osdu-data
  resourceVersion: "8130518"
  uid: 433c4db5-2827-4dcd-bc5c-63545fe92fe8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: opensearch-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-01-27T13:23:46+07:00"
      creationTimestamp: null
      labels:
        app: opensearch-proxy
    spec:
      containers:
      - image: nginx:1.25-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9200
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nginx
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9200
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: config
          readOnly: true
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: opensearch-proxy-config
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-01-26T10:02:22Z"
    lastUpdateTime: "2026-01-26T10:02:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-01-26T10:02:16Z"
    lastUpdateTime: "2026-01-27T06:23:56Z"
    message: ReplicaSet "opensearch-proxy-5dbfdc6cdb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
