apiVersion: v1
data:
  access-token: X19SRVBMQUNFX01FX18=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"access-token":"X19SRVBMQUNFX01FX18="},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":null,"name":"digitalocean","namespace":"kube-system"}}
  creationTimestamp: "2025-12-27T06:19:38Z"
  name: digitalocean
  namespace: kube-system
  resourceVersion: "490934"
  uid: 44eb3473-3321-4922-aa2b-661629c166cb
type: Opaque
