apiVersion: v1
kind: Service
metadata:
  name: partition
  labels:
    app: osdu-partition
    purpose: alias-for-secret-service
spec:
  type: ExternalName
  externalName: osdu-partition.osdu-core.svc.cluster.local
