apiVersion: v1
kind: Service
metadata:
  name: osdu-secret
  labels:
    app: osdu-secret
spec:
  selector:
    app: osdu-secret
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
