apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-crs-conversion
  labels:
    app: osdu-crs-conversion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osdu-crs-conversion
  template:
    metadata:
      labels:
        app: osdu-crs-conversion
    spec:
      containers:
        - name: crs-conversion
          image: community.opengroup.org:5555/osdu/platform/system/reference/crs-conversion-service/core-plus-crs-conversion-release:a21cfb41
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: osdu-core-env
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "anthos"
            - name: SERVER_PORT
              value: "8080"
            - name: AUTHORIZE_API
              value: "http://osdu-entitlements:8080/api/entitlements/v2"
            - name: ENTITLEMENTS_HOST
              value: "http://osdu-entitlements:8080"
            - name: ENTITLEMENTS_PATH
              value: "/api/entitlements/v2/"
            - name: CRS_CATALOG_URL
              value: "http://osdu-crs-catalog:8080/api/crs/catalog"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 20
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
