apiVersion: v1
kind: Service
metadata:
  name: osdu-workflow
  labels:
    app: osdu-workflow
    app.kubernetes.io/name: workflow
    app.kubernetes.io/part-of: osdu
spec:
  selector:
    app: osdu-workflow
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
