apiVersion: v1
kind: Service
metadata:
  name: osdu-notification
  labels:
    app: osdu-notification
    app.kubernetes.io/name: notification
    app.kubernetes.io/part-of: osdu
spec:
  selector:
    app: osdu-notification
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
