apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: osdu
  name: osdu-core
---
apiVersion: v1
data:
  JAVA_OPTS: -Xms256m -Xmx512m
  KAFKA_BOOTSTRAP_SERVERS: osdu-kafka.osdu-data.svc.cluster.local:9092
  KEYCLOAK_ISSUER_URI: http://keycloak.osdu-identity.svc.cluster.local/realms/osdu
  OPENSEARCH_HOST: osdu-opensearch.osdu-data.svc.cluster.local
  OPENSEARCH_PORT: "9200"
  PARTITION_API: http://osdu-partition:8080/api/partition/v1
  POSTGRES_HOST: osdu-postgres.osdu-data.svc.cluster.local
  POSTGRES_PORT: "5432"
  REDIS_GROUP_HOST: osdu-redis.osdu-data.svc.cluster.local
  REDIS_GROUP_PORT: "6379"
  REDIS_HOST: osdu-redis.osdu-data.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_STORAGE_HOST: osdu-redis.osdu-data.svc.cluster.local
  REDIS_STORAGE_PORT: "6379"
  SERVER_PORT: "8080"
kind: ConfigMap
metadata:
  name: osdu-core-env
  namespace: osdu-core
---
apiVersion: v1
data:
  env: do-private
  note: Created by Step17
  owner: gitops
kind: ConfigMap
metadata:
  name: osdu-core-marker
  namespace: osdu-core
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: osdu-core
spec:
  externalName: keycloak.osdu-identity.svc.cluster.local
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: osdu-entitlements
  name: osdu-entitlements
  namespace: osdu-core
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: osdu-entitlements
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: osdu-file
  name: osdu-file
  namespace: osdu-core
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: osdu-file
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: osdu-legal
  name: osdu-legal
  namespace: osdu-core
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: osdu-legal
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: osdu-partition
  name: osdu-partition
  namespace: osdu-core
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: osdu-partition
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: osdu-schema
  name: osdu-schema
  namespace: osdu-core
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: osdu-schema
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: osdu-storage
  name: osdu-storage
  namespace: osdu-core
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: osdu-storage
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: osdu-entitlements
  name: osdu-entitlements
  namespace: osdu-core
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: osdu-entitlements
  template:
    metadata:
      labels:
        app: osdu-entitlements
    spec:
      containers:
      - env:
        - name: PARTITION_API
          value: http://osdu-partition:8080/api/partition/v1
        - name: KEYCLOAK_ISSUER_URI
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_ISSUER_URI
              name: osdu-core-env
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          value: $(KEYCLOAK_ISSUER_URI)
        - name: REDIS_USER_INFO_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_HOST
              name: osdu-core-env
        - name: REDIS_USER_INFO_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT
              name: osdu-core-env
        - name: REDIS_USER_GROUPS_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_HOST
              name: osdu-core-env
        - name: REDIS_USER_GROUPS_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT
              name: osdu-core-env
        - name: ENTITLEMENTS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: osdu-postgres-secret
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_HOST
              name: osdu-core-env
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PORT
              name: osdu-core-env
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/entitlements
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: osdu-postgres-secret
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: osdu-postgres-secret
        - name: ENTITLEMENTS_AUTH_ENABLED
          value: "false"
        envFrom:
        - configMapRef:
            name: osdu-core-env
        image: community.opengroup.org:5555/osdu/platform/security-and-compliance/entitlements/core-plus-entitlements-v2-release:9e5865f1
        imagePullPolicy: IfNotPresent
        name: entitlements
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          tcpSocket:
            port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: osdu-file
  name: osdu-file
  namespace: osdu-core
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: osdu-file
  template:
    metadata:
      labels:
        app: osdu-file
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/file
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: osdu-postgres-secret
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: osdu-postgres-secret
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          value: $(KEYCLOAK_ISSUER_URI)
        - name: PARTITION_SERVICE_ENDPOINT
          value: http://osdu-partition:8080
        - name: CLOUD_PROVIDER
          value: minio
        - name: FILE_AUTH_ENABLED
          value: "false"
        envFrom:
        - configMapRef:
            name: osdu-core-env
        - secretRef:
            name: osdu-objectstore-secret
        image: community.opengroup.org:5555/osdu/platform/system/file/core-plus-file-release:8531906d
        imagePullPolicy: IfNotPresent
        name: file
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          tcpSocket:
            port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: osdu-legal
  name: osdu-legal
  namespace: osdu-core
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: osdu-legal
  template:
    metadata:
      labels:
        app: osdu-legal
    spec:
      containers:
      - env:
        - name: PARTITION_HOST
          value: http://osdu-partition:8080
        - name: PARTITION_API
          value: http://osdu-partition:8080/api/partition/v1
        - name: ENTITLEMENTS_HOST
          value: http://osdu-entitlements:8080
        - name: ENTITLEMENTS_URL
          value: http://osdu-entitlements:8080/api/entitlements/v2
        - name: AUTHORIZE_API
          value: http://osdu-entitlements:8080/api/entitlements/v2
        - name: OBM_MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: SecretKey
              name: rook-ceph-object-user-osdu-store-osdu-s3-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: osdu-postgres-secret
        - name: LOG_LEVEL
          value: INFO
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/legal
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: osdu-postgres-secret
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: osdu-postgres-secret
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          value: $(KEYCLOAK_ISSUER_URI)
        - name: PARTITION_SERVICE_ENDPOINT
          value: http://osdu-partition:8080
        - name: LEGAL_AUTH_ENABLED
          value: "false"
        envFrom:
        - configMapRef:
            name: osdu-core-env
        image: community.opengroup.org:5555/osdu/platform/security-and-compliance/legal/core-plus-legal-release:340be643
        imagePullPolicy: IfNotPresent
        name: legal
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          tcpSocket:
            port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: osdu-partition
  name: osdu-partition
  namespace: osdu-core
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: osdu-partition
  template:
    metadata:
      labels:
        app: osdu-partition
    spec:
      containers:
      - env:
        - name: KEYCLOAK_ISSUER_URI
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_ISSUER_URI
              name: osdu-core-env
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          value: $(KEYCLOAK_ISSUER_URI)
        - name: PARTITION_POSTGRES_URL
          value: jdbc:postgresql://osdu-postgres.osdu-data.svc.cluster.local:5432/partition
        - name: PARTITION_POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: osdu-postgres-secret
        - name: PARTITION_POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: osdu-postgres-secret
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/partition
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: osdu-postgres-secret
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: osdu-postgres-secret
        - name: PARTITION_AUTH_ENABLED
          value: "false"
        - name: CLOUD_PROVIDER
          value: minio
        envFrom:
        - configMapRef:
            name: osdu-core-env
        image: community.opengroup.org:5555/osdu/platform/system/partition/core-plus-partition-release:923ea1cd
        imagePullPolicy: IfNotPresent
        name: partition
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          tcpSocket:
            port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: osdu-schema
  name: osdu-schema
  namespace: osdu-core
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: osdu-schema
  template:
    metadata:
      labels:
        app: osdu-schema
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/schema
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: osdu-postgres-secret
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: osdu-postgres-secret
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          value: $(KEYCLOAK_ISSUER_URI)
        - name: PARTITION_SERVICE_ENDPOINT
          value: http://osdu-partition:8080
        - name: SCHEMA_AUTH_ENABLED
          value: "false"
        envFrom:
        - configMapRef:
            name: osdu-core-env
        image: community.opengroup.org:5555/osdu/platform/system/schema-service/core-plus-schema-release:b19664d2
        imagePullPolicy: IfNotPresent
        name: schema
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          tcpSocket:
            port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: osdu-storage
  name: osdu-storage
  namespace: osdu-core
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: osdu-storage
  template:
    metadata:
      labels:
        app: osdu-storage
    spec:
      containers:
      - env:
        - name: OQM_DRIVER
          value: kafka
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: osdu-redpanda.osdu-data.svc.cluster.local:9092
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_HOST
              name: osdu-core-env
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT
              name: osdu-core-env
        - name: CACHE_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_HOST
              name: osdu-core-env
        - name: CACHE_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT
              name: osdu-core-env
        - name: CACHE_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_HOST
              name: osdu-core-env
        - name: CACHE_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT
              name: osdu-core-env
        - name: SPRING_DATA_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_HOST
              name: osdu-core-env
        - name: SPRING_DATA_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT
              name: osdu-core-env
        - name: REDIS_GROUP_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_HOST
              name: osdu-core-env
        - name: REDIS_GROUP_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT
              name: osdu-core-env
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_HOST
              name: osdu-core-env
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PORT
              name: osdu-core-env
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/storage
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: osdu-postgres-secret
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: osdu-postgres-secret
        - name: KEYCLOAK_ISSUER_URI
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_ISSUER_URI
              name: osdu-core-env
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_ISSUER_URI
              name: osdu-core-env
        - name: OPENID_PROVIDER_URL
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_ISSUER_URI
              name: osdu-core-env
        - name: OPENID_PROVIDER_ISSUER
          valueFrom:
            configMapKeyRef:
              key: KEYCLOAK_ISSUER_URI
              name: osdu-core-env
        - name: OPENID_PROVIDER_CLIENT_ID
          value: osdu
        - name: OPENID_PROVIDER_CLIENT_SECRET
          value: dummy-secret-value
        - name: OPENID_PROVIDER_SCOPES
          value: openid profile email
        - name: PARTITION_API
          value: http://osdu-partition:8080/api/partition/v1
        - name: STORAGE_AUTH_ENABLED
          value: "false"
        - name: CLOUD_PROVIDER
          value: minio
        - name: JAVA_TOOL_OPTIONS
          value: -Dcache.host=osdu-redis.osdu-data.svc.cluster.local -Dcache.port=6379
        - name: SPRING_APPLICATION_JSON
          value: '{"cache":{"redis":{"host":"osdu-redis.osdu-data.svc.cluster.local","port":6379},"host":"osdu-redis.osdu-data.svc.cluster.local","port":6379}}'
        envFrom:
        - configMapRef:
            name: osdu-core-env
        - secretRef:
            name: osdu-objectstore-secret
        - secretRef:
            name: osdu-core-secrets
            optional: true
        image: community.opengroup.org:5555/osdu/platform/system/storage/core-plus-storage-core-plus-release:dcc4c072
        imagePullPolicy: IfNotPresent
        name: storage
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          tcpSocket:
            port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-toolbox
  namespace: osdu-core
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: osdu-toolbox
  template:
    metadata:
      labels:
        app: osdu-toolbox
    spec:
      containers:
      - args:
        - sleep infinity
        command:
        - sh
        - -c
        image: postgres:16-alpine
        imagePullPolicy: IfNotPresent
        name: toolbox
